/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.safpackager;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author john
 */
public class Builder extends javax.swing.JFrame {

    /**
     * Creates new form Builder
     */
    public Builder() {
        super("OU - Libraries");
        initComponents();
        com.apple.eawt.Application.getApplication().setDockIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
    }

    private String abstractPath = null;
    private String pathToSave = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblHomeLogo = new javax.swing.JLabel();
        lblHomeApplication = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSAFOpenCSV = new javax.swing.JButton();
        lblSAFCSVPath = new javax.swing.JLabel();
        btnSAFGenerateSAF = new javax.swing.JButton();
        lblSAFAlert = new javax.swing.JLabel();
        btnSAFSelectPath = new javax.swing.JButton();
        lblSAFSelectedSavePath = new javax.swing.JLabel();
        lblSAFOutputDir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHelpPrepareData = new javax.swing.JLabel();
        lblHelpGenerateSAF = new javax.swing.JLabel();
        lblHelpSampleCSV = new javax.swing.JLabel();
        lblHelpCSVTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(120, 120, 570, 300));
        setLocation(new java.awt.Point(30, 23));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblHomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        lblHomeApplication.setFont(new java.awt.Font("Lucida Grande", 1, 72)); // NOI18N
        lblHomeApplication.setText("SAFBuilder");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblHomeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblHomeLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblHomeApplication)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Home", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSAFOpenCSV.setText("Open a csv file");
        btnSAFOpenCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAFOpenCSVActionPerformed(evt);
            }
        });

        btnSAFGenerateSAF.setText("Generate SAF");
        btnSAFGenerateSAF.setVisible(false);
        btnSAFGenerateSAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAFGenerateSAFActionPerformed(evt);
            }
        });

        btnSAFSelectPath.setText("Select path to save");
        btnSAFSelectPath.setVisible(false);
        btnSAFSelectPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAFSelectPathActionPerformed(evt);
            }
        });

        lblSAFSelectedSavePath.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSAFOutputDir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSAFSelectPath)
                            .addComponent(lblSAFAlert)
                            .addComponent(btnSAFGenerateSAF)
                            .addComponent(btnSAFOpenCSV))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSAFCSVPath, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSAFSelectedSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSAFGenerateSAF, btnSAFOpenCSV, btnSAFSelectPath});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSAFCSVPath, lblSAFSelectedSavePath});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSAFOpenCSV)
                    .addComponent(lblSAFCSVPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSAFAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSAFSelectPath)
                    .addComponent(lblSAFSelectedSavePath))
                .addGap(10, 10, 10)
                .addComponent(btnSAFGenerateSAF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSAFOutputDir)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tabbedPane.addTab("SAF", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblHelpPrepareData.setText("<html> <b>How to prepare data:</b><br/> 1) A csv metadata file (See sample below)<br/> 2) PDF or other files must be in the same directory with the csv<br/> 3) The header of column for files must be named as \"filename\"<br/> 4) Use || to separate file names if an item has multiple files<br/> 5) Dublin core metadata starts with \"dc\", custom non dublin core metadata has formats like \"ou.group\" or \"ou.group.faculty\" <br/> </html>");

        lblHelpGenerateSAF.setText("<html> <b>How to generate SAF package:</b><br/> 1) In the SAF tab, open the csv containing your metadata<br/> 2) Press Generate SAF button which appears if the opened file is a csv<br/> 3) Verify the location of the SAF package </html>");

        lblHelpSampleCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/headers.png"))); // NOI18N

        lblHelpCSVTitle.setText("sample csv file: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHelpPrepareData, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHelpCSVTitle)
                            .addComponent(lblHelpGenerateSAF, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHelpSampleCSV))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelpPrepareData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelpCSVTitle)
                .addGap(3, 3, 3)
                .addComponent(lblHelpSampleCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelpGenerateSAF)
                .addContainerGap())
        );

        tabbedPane.addTab("Help", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSAFGenerateSAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAFGenerateSAFActionPerformed
        if (abstractPath != null) {
            SAFPackage safPackageInstance = new SAFPackage();
            pathToSave = lblSAFSelectedSavePath.getText();
            try {
                safPackageInstance.processMetaPack(abstractPath, pathToSave, true);
                lblSAFOutputDir.setText(safPackageInstance.getOutputString());
            } catch (IOException ex) {
                Logger.getLogger(Builder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSAFGenerateSAFActionPerformed

    private void btnSAFOpenCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAFOpenCSVActionPerformed

        btnSAFGenerateSAF.setVisible(false);
        btnSAFSelectPath.setVisible(false);
        lblSAFSelectedSavePath.setVisible(false);
        lblSAFOutputDir.setText("");

        JFileChooser fc = new JFileChooser();

        String fileName;
        int r = fc.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            fileName = file.getName();
            abstractPath = fc.getSelectedFile().getAbsolutePath();
            lblSAFCSVPath.setText(abstractPath);

            if ("csv".equals(getExtensionByApacheCommonLib(fileName))) {
                lblSAFAlert.setText("");
                btnSAFSelectPath.setVisible(true);
                lblSAFSelectedSavePath.setVisible(true);
                lblSAFSelectedSavePath.setText(fc.getSelectedFile().getParent());
                btnSAFGenerateSAF.setVisible(true);
            } else {
                lblSAFAlert.setText("This is not a csv file");
            }
        }
    }//GEN-LAST:event_btnSAFOpenCSVActionPerformed

    private void btnSAFSelectPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAFSelectPathActionPerformed
        JFileChooser chooser = new JFileChooser();
        String choosertitle = "Select a Directory";
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            pathToSave = chooser.getSelectedFile().toString();
            lblSAFSelectedSavePath.setText(pathToSave);
        }
    }//GEN-LAST:event_btnSAFSelectPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Builder.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Builder.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Builder.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Builder.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Builder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSAFGenerateSAF;
    private javax.swing.JButton btnSAFOpenCSV;
    private javax.swing.JButton btnSAFSelectPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHelpCSVTitle;
    private javax.swing.JLabel lblHelpGenerateSAF;
    private javax.swing.JLabel lblHelpPrepareData;
    private javax.swing.JLabel lblHelpSampleCSV;
    private javax.swing.JLabel lblHomeApplication;
    private javax.swing.JLabel lblHomeLogo;
    private javax.swing.JLabel lblSAFAlert;
    private javax.swing.JLabel lblSAFCSVPath;
    private javax.swing.JLabel lblSAFOutputDir;
    private javax.swing.JLabel lblSAFSelectedSavePath;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private String getExtensionByApacheCommonLib(String filename) {
        return FilenameUtils.getExtension(filename);
    }
}
